<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Scan QR to payDownload QR CodeBack</name>
   <tag></tag>
   <elementGuidId>1bde5c5d-c4ed-4909-ad31-d882ad3ac234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div/div[2]/section/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-col.items-center.space-y-8.py-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bae68f90-229c-4d9e-b90e-3ddd56cbb732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col items-center space-y-8 py-8</value>
      <webElementGuid>6fc781ed-80e4-4b1b-ada9-3ea7fbda7156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Scan QR to payDownload QR CodeBack</value>
      <webElementGuid>7c5232fb-ceb9-49a9-97b0-868a293fbe26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;min-h-screen flex items-stretch text-base text-xen-gray-900&quot;]/div[@class=&quot;flex-1 lg:px-8 xl:px-8 lg:py-8 min-h-screen&quot;]/div[@class=&quot;w-full h-full mx-auto lg:max-w-2xl flex flex-col&quot;]/div[@class=&quot;flex-1&quot;]/section[@class=&quot;pt-8 pb-12 px-4 lg:px-0 max-w-screen-sm mx-auto&quot;]/div[@class=&quot;flex flex-col items-center space-y-8 py-8&quot;]</value>
      <webElementGuid>27e8e83b-2053-475a-8b07-1bfafed93bb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/section/div</value>
      <webElementGuid>2dacc418-4810-4455-9c1a-2d4650b2e2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div</value>
      <webElementGuid>ff6c6491-8098-4a0c-9410-0e2bd02be168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Scan QR to payDownload QR CodeBack' or . = 'Scan QR to payDownload QR CodeBack')]</value>
      <webElementGuid>15b2520f-c14e-4e44-87d3-7022bf571e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
