<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HUMAN RESOURCE SERIES SHORT CLASSIntro _14a967</name>
   <tag></tag>
   <elementGuidId>fdccfd69-a296-4dbf-8c9c-73aa8f0ba6d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiPaper-root.MuiPaper-elevation.MuiPaper-rounded.MuiPaper-elevation0.MuiAlert-root.MuiAlert-standardInfo.MuiAlert-standard.mui-style-7h2dhs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>741df700-c133-4992-b061-48819de4f5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation0 MuiAlert-root MuiAlert-standardInfo MuiAlert-standard mui-style-7h2dhs</value>
      <webElementGuid>b601eea2-a709-4fa7-a132-1512541f70bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>d6a08835-0262-4026-ad8b-63eef76852ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HUMAN RESOURCE SERIES: SHORT CLASSIntro to People Analytics Timeline Kegiatan13 Februari 2024 - 13 Februari 2024Biaya PendaftaranRp 0</value>
      <webElementGuid>8c42ed79-445e-4392-b736-5d3ad821c5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;notranlsate&quot;]/body[1]/div[@class=&quot;MuiDialog-root MuiModal-root mui-style-126xj0f&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper mui-style-16u656j&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm MuiDialog-paperFullWidth mui-style-2mum2w&quot;]/div[@class=&quot;MuiDialogContent-root mui-style-jkrf21&quot;]/div[@class=&quot;MuiStack-root mui-style-1ov46kg&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation0 MuiAlert-root MuiAlert-standardInfo MuiAlert-standard mui-style-7h2dhs&quot;]</value>
      <webElementGuid>ff9300c0-d12e-4bac-9619-1774e7f4dc11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]</value>
      <webElementGuid>5e78fa7b-973e-436e-a8f2-5c471c87dcba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'HUMAN RESOURCE SERIES: SHORT CLASSIntro to People Analytics Timeline Kegiatan13 Februari 2024 - 13 Februari 2024Biaya PendaftaranRp 0' or . = 'HUMAN RESOURCE SERIES: SHORT CLASSIntro to People Analytics Timeline Kegiatan13 Februari 2024 - 13 Februari 2024Biaya PendaftaranRp 0')]</value>
      <webElementGuid>be77f302-010e-4f3d-a44c-55ec91c87eef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
