<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar</name>
   <tag></tag>
   <elementGuidId>d9b7e01c-1b3a-46de-ad54-f45e3b170ec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/div/div[2]/div/div[3]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.wzgwUg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5e30bcb6-4fcc-4683-8839-efce52b24005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wzgwUg</value>
      <webElementGuid>ef661e8e-e796-4824-bae3-b9f94d63441b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/buyer/signup?next=https%3A%2F%2Fshopee.co.id%2F</value>
      <webElementGuid>740abcc5-2c7d-4a01-9cc2-0b84a794424d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>d33db8b1-8e93-4acf-8daa-3d14404c2b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;vtexOX&quot;]/div[1]/div[@class=&quot;_3M9lzn PeA8Gc&quot;]/div[@class=&quot;Gxi65y&quot;]/div[2]/div[@class=&quot;IxqCyD J1i6cp B-fiUo&quot;]/div[@class=&quot;XLzpXt&quot;]/div[@class=&quot;Oug9xv Z8OMtU&quot;]/a[@class=&quot;wzgwUg&quot;]</value>
      <webElementGuid>ad339e4b-d4ee-47df-ac37-7c98e7d264eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div/div[2]/div/div[3]/div/a</value>
      <webElementGuid>9b9e1ffe-018a-4536-9634-edc1e03828eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daftar')]</value>
      <webElementGuid>c037308f-c2ec-4cca-9cce-af9833a38093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/buyer/signup?next=https%3A%2F%2Fshopee.co.id%2F')]</value>
      <webElementGuid>53e5907f-c5f7-4515-9b26-66c478c24552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>161b1752-d53d-4259-bb03-ec95bd567ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/buyer/signup?next=https%3A%2F%2Fshopee.co.id%2F' and (text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>64bd5d3b-7490-43cd-9759-bbee79ae2977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
