<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Password kamu telah berhasil diubah</name>
   <tag></tag>
   <elementGuidId>4a75085f-884c-48a3-9d83-69a5d09e8ea2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/form/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiDialogContent-root.mui-style-jkrf21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3479b729-d89a-4f82-88bd-b8f92b19199b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiDialogContent-root mui-style-jkrf21</value>
      <webElementGuid>4ca32686-cea2-4563-b043-c3e1bde26fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password kamu telah berhasil diubah.</value>
      <webElementGuid>c8c531bd-ea86-4efb-8552-07b2c63d811b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;notranlsate&quot;]/body[1]/div[@class=&quot;MuiDialog-root MuiModal-root mui-style-126xj0f&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper mui-style-16u656j&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm MuiDialog-paperFullWidth mui-style-2mum2w&quot;]/form[1]/div[@class=&quot;MuiDialogContent-root mui-style-jkrf21&quot;]</value>
      <webElementGuid>83e67a96-b2a9-4294-9edd-b5c4f1bac091</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/div</value>
      <webElementGuid>f3187b99-3775-47c9-b76a-c0f41d8b8823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Password kamu telah berhasil diubah.' or . = 'Password kamu telah berhasil diubah.')]</value>
      <webElementGuid>2aabaeab-d7c8-4ba6-aadb-03280e8c8300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/div/div</value>
      <webElementGuid>08694333-c9b3-44b8-9cd6-a343950a7b32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
