<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_confirmNewPassword</name>
   <tag></tag>
   <elementGuidId>5e3715da-084d-4ac1-a6e2-b45c323c55ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=':rv:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f29ac86b-c9cf-4cab-9fe7-f09e59a62c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0053865b-a792-4b74-82c9-f7cde30bdce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rv:</value>
      <webElementGuid>bed1f521-d6e7-4c02-aef1-8ef265c6b155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmNewPassword</value>
      <webElementGuid>ef653326-5409-4909-a0ab-e6a1a39870ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6cc7278d-f991-41a2-874d-8f38a62a7dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiFilledInput-input MuiInputBase-inputHiddenLabel MuiInputBase-inputAdornedEnd mui-style-zuxsip</value>
      <webElementGuid>e1775de2-6879-41d5-9f08-c55ee6d86a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rv:&quot;)</value>
      <webElementGuid>71a8eba4-5e32-465a-a991-0f84ac116fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id=':rv:']</value>
      <webElementGuid>e564b320-6bc3-46f0-ace8-456dc5849471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/input</value>
      <webElementGuid>bc5b7c5e-2e6d-4fa4-8801-bae436e9582e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = ':rv:' and @name = 'confirmNewPassword' and @type = 'password']</value>
      <webElementGuid>c9373046-9f2b-46f3-94b3-56ce13b221d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
