<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Berhasil logout, sampai jumpa kembali</name>
   <tag></tag>
   <elementGuidId>3a69a17d-01b4-44ee-9655-0ac060eae139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notistack-snackbar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notistack-snackbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f297cfb6-1a8d-4398-974f-1ce4a51ebb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notistack-snackbar</value>
      <webElementGuid>1979c3bc-da8a-4f8d-9fe5-1566aedb52e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SnackbarItem-message</value>
      <webElementGuid>7adcadbb-ce90-4b7b-8b25-973bc190cb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berhasil logout, sampai jumpa kembali!</value>
      <webElementGuid>ce3e4490-04ae-45d7-b034-0abac312bd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notistack-snackbar&quot;)</value>
      <webElementGuid>eae84153-cd55-45bb-b252-7e292a66e07b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='notistack-snackbar']</value>
      <webElementGuid>3d77bce4-2f22-43d0-83f2-b7f0c66a9860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>601f4a40-8910-4c9d-be05-0427a080fbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>ccaa1815-3ea1-4c43-bc64-49e4f41870f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'notistack-snackbar' and (text() = 'Berhasil logout, sampai jumpa kembali!' or . = 'Berhasil logout, sampai jumpa kembali!')]</value>
      <webElementGuid>0cbe4837-6ba6-4960-9021-6a897e8410b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
