<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Email must be a valid email address</name>
   <tag></tag>
   <elementGuidId>d3e55525-1308-487e-8e52-610bf568c3a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':r0:-helper-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>30ae63ab-99f3-4aa2-850a-fec23272b314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained mui-style-egb5nh</value>
      <webElementGuid>ac1c0cd6-e28b-4425-b028-7edaa549a10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r0:-helper-text</value>
      <webElementGuid>2f528300-526d-44b0-88ed-7006b0ecfb55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email must be a valid email address</value>
      <webElementGuid>dc0ba957-ff76-4342-850a-e8957cf6ce54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r0:-helper-text&quot;)</value>
      <webElementGuid>71f13aa4-624b-48e5-89fb-4a3f9e48d33a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r0:-helper-text']</value>
      <webElementGuid>c0f39aa7-8c38-4fc3-91d2-00a61e9d8d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/form/div/div/p</value>
      <webElementGuid>137224bd-693f-4512-984f-15c86e67aa39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/p</value>
      <webElementGuid>26f244c6-8172-4061-a71f-472cb123d466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r0:-helper-text' and (text() = 'Email must be a valid email address' or . = 'Email must be a valid email address')]</value>
      <webElementGuid>7b8a0f0c-d975-4a42-83bf-9cb6d0dd81c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
