<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kirim ke WhatsApp</name>
   <tag></tag>
   <elementGuidId>a74da32a-a5d6-44b7-8a54-e2443028b2a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal']/aside/div/div/div[2]/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.wyhvVD._1EApiB.gSuZ93</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>537eec20-5e6e-4e1e-9a0b-4b35ee69fd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wyhvVD _1EApiB gSuZ93</value>
      <webElementGuid>e8c49b3e-cbfe-4b9b-a7d8-6f801867d647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim ke WhatsApp</value>
      <webElementGuid>c6274709-f553-4e70-9ddc-335c65d04418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)/aside[@class=&quot;jwVUSR&quot;]/div[@class=&quot;c7huf3 undefined&quot;]/div[@class=&quot;aZ-vOM&quot;]/div[@class=&quot;Kp5gjr zfb33O&quot;]/button[@class=&quot;wyhvVD _1EApiB gSuZ93&quot;]</value>
      <webElementGuid>ea40aed8-65f8-4c97-a98f-1a57ccd98287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal']/aside/div/div/div[2]/button[3]</value>
      <webElementGuid>a960a20c-032f-4fcd-b91f-eb0077716b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>689e4b5e-de64-42d4-9899-a0f3ee9759ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Kirim ke WhatsApp' or . = 'Kirim ke WhatsApp')]</value>
      <webElementGuid>97d50745-661a-40ac-8da1-d8034f39dc3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
