<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Konfirmasi password harus sama dengan password</name>
   <tag></tag>
   <elementGuidId>1d5ad2dc-1552-4e05-88b7-1ecbd2827fd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':r2:-helper-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>51b53948-2790-4d17-8068-c7ef1531d4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained MuiFormHelperText-filled mui-style-egb5nh</value>
      <webElementGuid>01240db2-f367-4c78-82be-d6f67171d247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r2:-helper-text</value>
      <webElementGuid>c91cc550-57bd-44eb-90e8-9e8f29c4a5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Konfirmasi password harus sama dengan password</value>
      <webElementGuid>ab909c5f-b1aa-4423-8364-b709e58cc8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r2:-helper-text&quot;)</value>
      <webElementGuid>9633e2ca-0654-4161-80ec-a22eee7e4510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r2:-helper-text']</value>
      <webElementGuid>19070f6a-af70-4a5c-918d-ad04d98d40a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/form/div/div[3]/p</value>
      <webElementGuid>d60b1ed6-0c4a-476b-9d8e-222c899fc983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>1f95e866-f518-4509-b170-ef7d93ca6463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r2:-helper-text' and (text() = 'Konfirmasi password harus sama dengan password' or . = 'Konfirmasi password harus sama dengan password')]</value>
      <webElementGuid>110c1056-cb82-44fd-8416-e3bb647256d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
