<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HomeE-learningBootcamp  ProgramMentorin_04f290</name>
   <tag></tag>
   <elementGuidId>151580d7-4f6a-4f57-8657-b34909d3fa7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiToolbar-root.MuiToolbar-regular.mui-style-1156eqb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9cf446c-40d5-4dab-8ad0-fb64751dc8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiToolbar-root MuiToolbar-regular mui-style-1156eqb</value>
      <webElementGuid>a34f86ac-0f6d-424e-acc9-df8fe6c0bec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HomeE-learningBootcamp &amp; ProgramMentoringCorporate ServiceBlogMasukDaftar</value>
      <webElementGuid>296998b0-cebb-475f-b9af-119403486ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiStack-root mui-style-o44is&quot;]/div[@class=&quot;MuiBox-root mui-style-1hvgntk&quot;]/div[@class=&quot;MuiBox-root mui-style-0&quot;]/div[1]/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation4 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionFixed mui-fixed mui-style-u5mgdq&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-regular mui-style-1156eqb&quot;]</value>
      <webElementGuid>adeedc2c-b295-4686-b1fc-53dcac9a71c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/header/div</value>
      <webElementGuid>af579a6c-06f7-4702-8e2f-e300cf6f3b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div</value>
      <webElementGuid>3f7f2aac-f695-4b92-811a-2a171d405a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'HomeE-learningBootcamp &amp; ProgramMentoringCorporate ServiceBlogMasukDaftar' or . = 'HomeE-learningBootcamp &amp; ProgramMentoringCorporate ServiceBlogMasukDaftar')]</value>
      <webElementGuid>3fa7c21e-6e36-4ac8-93b0-f82b84fff479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
