<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HomeE-learningBootcamp  ProgramMentorin_207484</name>
   <tag></tag>
   <elementGuidId>b822b1c4-a2c5-44d7-aead-d80b4cb4a28d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/header/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiToolbar-root.MuiToolbar-regular.mui-style-1156eqb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>95d6d9c1-21dd-404e-9a60-7cb377fcc6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiToolbar-root MuiToolbar-regular mui-style-1156eqb</value>
      <webElementGuid>467e5abc-bc86-42b4-ab82-aadea838512b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HomeE-learningBootcamp &amp; ProgramMentoringCorporate ServiceBlog</value>
      <webElementGuid>9a5ed118-eb64-4561-a5dc-90962d0aafce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiStack-root mui-style-o44is&quot;]/div[@class=&quot;MuiBox-root mui-style-1hvgntk&quot;]/div[@class=&quot;MuiBox-root mui-style-0&quot;]/div[1]/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation4 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionFixed mui-fixed mui-style-u5mgdq&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-regular mui-style-1156eqb&quot;]</value>
      <webElementGuid>e5bbc4ec-c7cb-4e03-881e-aa87d4f37bf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/header/div</value>
      <webElementGuid>311238fc-03e1-46a1-9d2b-f6fb49081a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div</value>
      <webElementGuid>6df81cff-594e-4d2f-acde-a364f68c773f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'HomeE-learningBootcamp &amp; ProgramMentoringCorporate ServiceBlog' or . = 'HomeE-learningBootcamp &amp; ProgramMentoringCorporate ServiceBlog')]</value>
      <webElementGuid>24cb08d4-ea93-4039-923b-3cf9c7300004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/header/div/div</value>
      <webElementGuid>39f80055-b2de-41d3-89d9-05a47d8556ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div</value>
      <webElementGuid>d19aed2d-d95f-459c-9ced-435d84d1b660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
