<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Batch Free E-Book Kitab Sakti Tembus Bea_4db092</name>
   <tag></tag>
   <elementGuidId>1bc642a8-5fa5-44fd-b248-6619cc3b1902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id=':rg:']/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.MuiButtonBase-root.MuiMenuItem-root.MuiMenuItem-gutters.MuiMenuItem-root.MuiMenuItem-gutters.mui-style-1azjkcz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>00757822-05db-4ad5-8ed5-8308a90c7847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiMenuItem-root MuiMenuItem-gutters mui-style-1azjkcz</value>
      <webElementGuid>e8fa4f2d-6f83-49bd-a932-f59d69da456e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>38442b29-b4cc-4b1e-87e4-003cc010caf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d216a091-9951-4055-8fff-3978c3ed4033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f65e195c-b02b-4c08-af2a-25be894cd1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>RtSfhLMboXT51ZGEnvwx</value>
      <webElementGuid>2b7b8248-0e44-4b37-97cf-c702752e6137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batch Free E-Book Kitab Sakti Tembus Beasiswa &amp; Kampus Luar Negeri.27 April 2023 - 30 April 2024</value>
      <webElementGuid>ec242f6c-ffa6-4a05-a5a8-c7ec54ec5526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rg:&quot;)/li[@class=&quot;MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiMenuItem-root MuiMenuItem-gutters mui-style-1azjkcz&quot;]</value>
      <webElementGuid>3e2cd9b7-e6d8-4ef4-bbed-e76d8ad61db8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id=':rg:']/li</value>
      <webElementGuid>59afcc5e-7aea-4a18-8d88-b51a7e9025d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li</value>
      <webElementGuid>abf92f1c-031e-4b80-ad2d-b65c1f96ee7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Batch Free E-Book Kitab Sakti Tembus Beasiswa &amp; Kampus Luar Negeri.27 April 2023 - 30 April 2024' or . = 'Batch Free E-Book Kitab Sakti Tembus Beasiswa &amp; Kampus Luar Negeri.27 April 2023 - 30 April 2024')]</value>
      <webElementGuid>9644dfc9-04c5-412d-9a64-96961d8ab384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
