<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar</name>
   <tag></tag>
   <elementGuidId>e7017e21-a25c-466c-b675-024b9ed7ecd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/header/div/div[2]/div/div/div/div/header/div/div/div[2]/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.rr___Button-module__button___boy9U.rr___Button-module__size_small___qOI91.rr___Button-module__horizontal_padding___BWmaZ.rr___Button-module__variant_primary___m8Teh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70f2046e-5d41-4c3a-a491-dc302d0ba1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rr___Button-module__button___boy9U rr___Button-module__size_small___qOI91 rr___Button-module__horizontal_padding___BWmaZ rr___Button-module__variant_primary___m8Teh</value>
      <webElementGuid>d025dc65-2193-45d0-a22e-47af112ced77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>a209c4c3-ec00-4b0c-85c1-e6a25eab0ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0a68bbd1-0968-4874-b9b2-2cb21ebd068c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>6afb139d-c0aa-4b5c-937f-b326c94d680f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;index_main___rT19&quot;]/header[@class=&quot;index_header__25ySr&quot;]/div[@class=&quot;index_header_inner__ZgIbg&quot;]/div[2]/div[1]/div[@class=&quot;rr___index-module__passport___yVJtE&quot;]/div[1]/div[@class=&quot;rr___Header-module__desktop_only___npH90 rr___Header-module__desktop_wrapper_without_bottom___nabMh&quot;]/header[@class=&quot;rr___HeaderDesktop-module__header___OdCjO rr___HeaderDesktop-module__transparent___uem9n&quot;]/div[@class=&quot;rr___Container-module__container___kYNEt&quot;]/div[@class=&quot;rr___HeaderDesktop-module__header_top___B8Fif&quot;]/div[@class=&quot;rr___HeaderDesktop-module__right___iAAHn&quot;]/a[@class=&quot;rr___Button-module__button___boy9U rr___Button-module__size_small___qOI91 rr___Button-module__horizontal_padding___BWmaZ rr___Button-module__variant_primary___m8Teh&quot;]</value>
      <webElementGuid>32561356-a25e-445b-85eb-fab1c10e9f01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/header/div/div[2]/div/div/div/div/header/div/div/div[2]/a[4]</value>
      <webElementGuid>b5006dc8-08ae-45e0-bd83-2edc6da0be61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daftar')]</value>
      <webElementGuid>51d4c064-7eac-4151-97b5-e98a577ea3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>128827a1-51c9-4a37-989c-4afe26544023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>9db47073-6d54-4b11-a097-d4993f9dac92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
