<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframecf-chl-widget-6lqsz</name>
   <tag></tag>
   <elementGuidId>d3be3432-c8b1-46e1-97f2-1d1ead66c3c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='cf-chl-widget-6lqsz']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cf-chl-widget-6lqsz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>512baba9-898a-4578-b961-b2c75e98e9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/6lqsz/0x4AAAAAAADnPIDROrmt1Wwj/dark/normal</value>
      <webElementGuid>a64172c2-db1c-477f-bc30-82cb13d19968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>cross-origin-isolated; fullscreen</value>
      <webElementGuid>d9ce11d4-34c4-43a4-947a-43fde326eddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-same-origin allow-scripts allow-popups</value>
      <webElementGuid>216ca877-4e52-4229-891a-51b8b4e22773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cf-chl-widget-6lqsz</value>
      <webElementGuid>30e650e4-c38a-403f-9328-c3f15841f50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e5e28fb6-6e86-4137-bcff-1e8addbf508f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Widget containing a Cloudflare security challenge</value>
      <webElementGuid>d83bc389-fb06-4c35-986f-8dca90b6644d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cf-chl-widget-6lqsz&quot;)</value>
      <webElementGuid>231bd5eb-9ce9-4271-974a-7e018c700c13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='cf-chl-widget-6lqsz']</value>
      <webElementGuid>66065a14-ba39-4ccd-9809-f439b3754577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='turnstile-wrapper']/div/iframe</value>
      <webElementGuid>5b9c355a-0a84-48bd-911d-84b8f45bf859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9c787e03-d9ad-4b00-bbf0-e9007e1d00bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/6lqsz/0x4AAAAAAADnPIDROrmt1Wwj/dark/normal' and @id = 'cf-chl-widget-6lqsz' and @title = 'Widget containing a Cloudflare security challenge']</value>
      <webElementGuid>512aedc1-dc07-4bb0-a667-ad263afd3101</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
