<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframecf-chl-widget-td728</name>
   <tag></tag>
   <elementGuidId>5333d35e-e01e-4290-8e2c-1537aa71dc42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='cf-chl-widget-td728']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cf-chl-widget-td728</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2117f689-0479-4ce8-936b-0a7e0bf36c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/td728/0x4AAAAAAADnPIDROrmt1Wwj/dark/normal</value>
      <webElementGuid>4d765511-cd58-4313-acc2-68d77b7b7946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>cross-origin-isolated; fullscreen</value>
      <webElementGuid>2556e1be-a5e6-4a67-8755-bd60fa6756a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-same-origin allow-scripts allow-popups</value>
      <webElementGuid>917eebac-58b7-469e-9bee-bee08d0c287f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cf-chl-widget-td728</value>
      <webElementGuid>4d25b766-e819-4ae8-9141-6f1cd8c5990c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>511989af-0c77-460c-8e01-d59b85da77ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Widget containing a Cloudflare security challenge</value>
      <webElementGuid>7b07db0d-8f39-4ee9-be6e-477ca5a5d6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cf-chl-widget-td728&quot;)</value>
      <webElementGuid>ecac047e-ab08-47c6-913b-0a4688df9d6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='cf-chl-widget-td728']</value>
      <webElementGuid>03670dfb-f92e-4525-bc00-67cf786573c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='turnstile-wrapper']/div/iframe</value>
      <webElementGuid>016d3311-356e-4580-9a37-38b50bdf75bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5364041c-51e4-4179-80df-9bad7ba0709c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/td728/0x4AAAAAAADnPIDROrmt1Wwj/dark/normal' and @id = 'cf-chl-widget-td728' and @title = 'Widget containing a Cloudflare security challenge']</value>
      <webElementGuid>08f00e22-6f4f-4078-a293-4fa81fc4eae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
