<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframecf-chl-widget-oj4an</name>
   <tag></tag>
   <elementGuidId>e60fc6db-fd46-43b3-92f5-c8228724835c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='cf-chl-widget-oj4an']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cf-chl-widget-oj4an</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cc6092b9-7e08-4429-b005-e983d3d1f2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/oj4an/0x4AAAAAAADnPIDROrmt1Wwj/dark/normal</value>
      <webElementGuid>41db6457-8a6b-4f5d-9a47-6d0b6db66d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>cross-origin-isolated; fullscreen</value>
      <webElementGuid>4665cb35-5adf-4977-9c59-9af885d48b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-same-origin allow-scripts allow-popups</value>
      <webElementGuid>a088641a-d57d-4290-b3ba-c8cbc9e8880d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cf-chl-widget-oj4an</value>
      <webElementGuid>7802ae22-d589-4761-a23b-2294c0b3011d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>722d37bc-5f6d-4f67-bc97-99dd005da580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Widget containing a Cloudflare security challenge</value>
      <webElementGuid>cee0d29b-772f-4f0c-9c20-73e8a7351834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cf-chl-widget-oj4an&quot;)</value>
      <webElementGuid>f9c7dafa-f0e8-46be-bdf3-a0a74a2fcfe1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='cf-chl-widget-oj4an']</value>
      <webElementGuid>d7ca1179-5909-4033-b559-d9f08632c7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='turnstile-wrapper']/div/iframe</value>
      <webElementGuid>3b1c3f2e-07c2-4366-82a1-3ddc94d2f240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c20a24ae-079a-4efe-b789-63aaf032c4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/oj4an/0x4AAAAAAADnPIDROrmt1Wwj/dark/normal' and @id = 'cf-chl-widget-oj4an' and @title = 'Widget containing a Cloudflare security challenge']</value>
      <webElementGuid>06fed521-4ff6-413a-adba-2bf79a4e51b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
