<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframecf-chl-widget-i5kbb</name>
   <tag></tag>
   <elementGuidId>e33cbf58-d7d5-4f44-af96-3d5ec669dd31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='cf-chl-widget-i5kbb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cf-chl-widget-i5kbb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ebf80602-4962-4319-b45e-5e527f7fff71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/i5kbb/0x4AAAAAAADnPIDROrmt1Wwj/dark/normal</value>
      <webElementGuid>2200db80-053d-4ce6-874a-70a9aeb67467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>cross-origin-isolated; fullscreen</value>
      <webElementGuid>9f5d94a4-93b9-4353-97bf-92d2740fbee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-same-origin allow-scripts allow-popups</value>
      <webElementGuid>4a59858b-af48-43e0-8f02-96d57385f267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cf-chl-widget-i5kbb</value>
      <webElementGuid>805c4aac-8484-42bd-80dc-e201cd0d60cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>03467ce3-0701-42b7-ae15-0f50c89f175a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Widget containing a Cloudflare security challenge</value>
      <webElementGuid>a902cd2c-7d4c-454b-aa21-7e6234174d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cf-chl-widget-i5kbb&quot;)</value>
      <webElementGuid>8b719e64-b94b-432c-a0ac-8c4de66a0763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='cf-chl-widget-i5kbb']</value>
      <webElementGuid>237120ed-4532-41d1-b3d2-be2fa1866b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='turnstile-wrapper']/div/iframe</value>
      <webElementGuid>f5b9f412-e625-42b4-81ea-0516a161bc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>294eab8b-2ed2-4baa-a1db-b645836afba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/i5kbb/0x4AAAAAAADnPIDROrmt1Wwj/dark/normal' and @id = 'cf-chl-widget-i5kbb' and @title = 'Widget containing a Cloudflare security challenge']</value>
      <webElementGuid>a97b2f78-b899-4820-9146-09941de80540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
