<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_mark</name>
   <tag></tag>
   <elementGuidId>45e18d06-d52b-4175-81d0-f94ec074c7a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='challenge-stage']/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>99da411d-2dea-405d-b730-5410b40782cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mark</value>
      <webElementGuid>fc189414-b086-45c6-92d9-a032d7b2794c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;challenge-stage&quot;)/div[@class=&quot;ctp-checkbox-container&quot;]/label[@class=&quot;ctp-checkbox-label&quot;]/span[@class=&quot;mark&quot;]</value>
      <webElementGuid>688eb2b5-a8d0-4def-b4a2-47e5e2c4558c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Just a moment/iframecf-chl-widget-6lqsz</value>
      <webElementGuid>3cbe86c5-e4bf-43c5-8bf7-955230dc7da8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='challenge-stage']/div/label/span</value>
      <webElementGuid>666d3d4f-6be5-4856-a862-bf49cef60c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>15eb4e93-4582-4c9d-9b3d-860f6c1cf812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
