<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Invoice berhasil dibuat, mengalihkan ke_e7bd1f</name>
   <tag></tag>
   <elementGuidId>661579fc-fc9e-48b8-9c0f-b781d81d2773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div/div[2]/div/div/div/div[4]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiAlert-message.mui-style-1dvysi1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a78d06a4-6268-4838-b20d-57d3b6860409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAlert-message mui-style-1dvysi1</value>
      <webElementGuid>37c04102-9818-4ff6-8039-259dc3af5c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invoice berhasil dibuat, mengalihkan ke halaman pembayaran dalam 5 detik...</value>
      <webElementGuid>f559cc9d-0e6f-4bf2-a7d9-5375b54a6235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiStack-root mui-style-o44is&quot;]/div[@class=&quot;MuiBox-root mui-style-lirq99&quot;]/div[@class=&quot;MuiBox-root mui-style-0&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg mui-style-1qsxih2&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-4 mui-style-1tz8m30&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-4 mui-style-19egsyp&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation0 MuiCard-root mui-style-wem97i&quot;]/div[@class=&quot;MuiCardContent-root mui-style-18mhetb&quot;]/div[@class=&quot;MuiStack-root mui-style-pb4y8c&quot;]/div[4]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation0 MuiAlert-root MuiAlert-standardSuccess MuiAlert-standard mui-style-fx7e5x&quot;]/div[@class=&quot;MuiAlert-message mui-style-1dvysi1&quot;]</value>
      <webElementGuid>4baa79a4-09a7-4d7d-b9d3-2c6145c440ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div[2]/div/div/div/div[4]/div/div[2]</value>
      <webElementGuid>09c560bd-13c6-4a2a-9a18-de3693c0b557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[4]/div/div[2]</value>
      <webElementGuid>c4f61d41-8d73-42f7-a12c-f31e4da71f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Invoice berhasil dibuat, mengalihkan ke halaman pembayaran dalam 5 detik...' or . = 'Invoice berhasil dibuat, mengalihkan ke halaman pembayaran dalam 5 detik...')]</value>
      <webElementGuid>fb25ae31-5367-482a-b960-fed67c8ad2da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
